### PR TITLE
Add a FontTransform to allow arbitrary transformations on glyphs.

### LINKED ISSUE #34: Font size is scalar
The `point_size` argument to `rasterize_glyph` (and `raster_bounds`) is a scalar, but in general we might need an affine transform (to apply fake-italic). If we used a full 3x2 affine, this would also subsume the `origin` argument.

### PR DESCRIPTION
**Pull request by jrmuizel**
Fixes #34

### CODE REVIEW

**Comment by pcwalton** [comment]
What do you think about replacing size with an affine transform?

**Comment by pcwalton** [comment]
Err, I mean a 2x2 transform.

**Comment by pcwalton** [comment]
Also I'm confused as to why font size needs to be different from scale…

**Comment by jrmuizel** [comment]
I'm not certain why, but all of the underlying system apis keep font size separate from the transform. I think it is probably wisest to just follow this convention.

**Comment by pcwalton** [comment]
Yeah, OK. I agree with wanting to follow the convention. @raphlinus Maybe you can shed some light on this?

**Comment by pcwalton** [comment]
This looks good when rebased, FWIW.

**Comment by jrmuizel** [comment]
Rebased. The test failure seems to be an intermittent.

**Pull request merged**
